server:
  port: 8080
app:
  artifactId: emp_timerecords
  version: 2.0
  
  # CouchBase DB URL
couchbaseDB:
  url: http://52.7.102.164:8091
  
spring:
  zipkin:
    base-url: ${ZIPKIN_URI:http://zipkin:8096}
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0
